export * from './growbeDashboardController.service';
import { GrowbeDashboardControllerService } from './growbeDashboardController.service';
export * from './growbeMainboardActionController.service';
import { GrowbeMainboardActionControllerService } from './growbeMainboardActionController.service';
export * from './growbeMainboardController.service';
import { GrowbeMainboardControllerService } from './growbeMainboardController.service';
export * from './growbeMainboardVersionController.service';
import { GrowbeMainboardVersionControllerService } from './growbeMainboardVersionController.service';
export * from './growbeModuleCalibrationController.service';
import { GrowbeModuleCalibrationControllerService } from './growbeModuleCalibrationController.service';
export * from './growbeModuleController.service';
import { GrowbeModuleControllerService } from './growbeModuleController.service';
export * from './growbeModuleDefController.service';
import { GrowbeModuleDefControllerService } from './growbeModuleDefController.service';
export * from './growbeModuleGraphController.service';
import { GrowbeModuleGraphControllerService } from './growbeModuleGraphController.service';
export * from './growbeStreamController.service';
import { GrowbeStreamControllerService } from './growbeStreamController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './userPreferenceController.service';
import { UserPreferenceControllerService } from './userPreferenceController.service';
export * from './virtualRelayController.service';
import { VirtualRelayControllerService } from './virtualRelayController.service';
export declare const APIS: (typeof GrowbeDashboardControllerService | typeof GrowbeMainboardActionControllerService | typeof GrowbeMainboardControllerService | typeof GrowbeMainboardVersionControllerService | typeof GrowbeModuleCalibrationControllerService | typeof GrowbeModuleControllerService | typeof GrowbeModuleDefControllerService | typeof GrowbeModuleGraphControllerService | typeof GrowbeStreamControllerService | typeof PingControllerService | typeof UserPreferenceControllerService | typeof VirtualRelayControllerService)[];
