export * from './growbeDashboardController.service';
import { GrowbeDashboardControllerService } from './growbeDashboardController.service';
export * from './growbeMainboardController.service';
import { GrowbeMainboardControllerService } from './growbeMainboardController.service';
export * from './growbeModuleGrowbeModuleDefController.service';
import { GrowbeModuleGrowbeModuleDefControllerService } from './growbeModuleGrowbeModuleDefController.service';
export * from './growbeWarningController.service';
import { GrowbeWarningControllerService } from './growbeWarningController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export const APIS = [GrowbeDashboardControllerService, GrowbeMainboardControllerService, GrowbeModuleGrowbeModuleDefControllerService, GrowbeWarningControllerService, PingControllerService];
