apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: growbe-cloud-watcher
  name: growbe-cloud-watcher
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: growbe-cloud-watcher
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: growbe-cloud-watcher
    spec:
      containers:
      - args:
        - node
        - dist/growbe-watcher.js
        env:
        - name: DB_URL
          value: postgres://test:test@pgsql:5432/defaultdb
        - name: MONGO_URL
          value: mongodb://doadmin:test@mongo:27018/growbe?authSource=admin
        - name: MQTT_URL
          value: mqtt://broker:{{ .Values.cloud.broker.port }}
        - name: PORT
          value: "3005"
        - name: SSO_URL
          value: http://sso:3001
        - name: DEBUG
          value: 'growbe:*'
        image: ghcr.io/growbe2/growbe-cloud/growbe-cloud:{{ .Values.cloud.version }}
        imagePullPolicy: Always
        name: growbe-cloud-watcher
        ports:
        - containerPort: 3005
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /live
            port: http
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghrc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}