apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: growbe-cloud
  name: growbe-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: growbe-cloud
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        io.kompose.service: growbe-cloud
    spec:
      containers:
      - args:
        - node
        - dist/growbe-cloud.js
        env:
        - name: DB_URL
          value: postgres://test:test@pgsql:5432/defaultdb
        - name: MONGO_URL
          value: mongodb://doadmin:test@mongo:27018/growbe?authSource=admin
        - name: MQTT_URL
          value: mqtt://broker:{{ .Values.cloud.broker.port }}
        - name: NMS_API_PASSWORD
          value: "12345678"
        - name: NMS_API_URL
          value: http://nms:8000
        - name: NMS_API_USERNAME
          value: testadmin
        - name: NMS_TOKEN
          value: "12345678"
        - name: PORT
          value: "3000"
        - name: SSO_URL
          value: http://sso:3001
        - name: DEBUG
          value: growbe:*
        - name: TZ
          value: "America/Toronto"
        - name: GITHUB_TOKEN_RO
          value: {{.Values.cloud.ghtoken}}
        - name: REVERSE_PROXY_ID_RSA
          value: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAgEAwbGwUEvVbv8jdDjLeBU9O3imM9qjcIUr43Xr/bNfailOvdXNYmPJ
            SuYoeFGrAR7jkMbbZW4XSd8o2w5Cgiv9bs/OCvgjk9M0Xj8534KVlKGAWJw5XN4ZKCVOGS
            dO9/bFv63A7PW597Q3KBXXIGnwkmV5y8k9vRHfO7lje+v0Nyje8D9p6O4wTSRQx+xpw2Ii
            aUnIJbo3+HTKZTrlJLDWK89Z8B2KVraM6edWZe6VfLEkv8+hqbgi5x+Fg4WeO9c54mAY6s
            Y4fCLBXTL9DQ9EarY48kTLl5Z3ntw7yGXs+CtGglnt3l+3DSL9djCz5puk9XybydzGCgla
            5FXxN5QI2WeljD22lB8YjgFiU+Cyt/g/EyaUm6rK0HVzPmMjBCivI14m0Q7UEIyonZCAkW
            QS3KJm9JHjVUkaabZPqCeuZAiQP1S9dGrNFgMYWm3CM0/+d7l7vRO8TyAQuF/XmHHnd2Tz
            aKyubwKroiRGcm2Fl0MMpAFFBDxOwC+OeIZ+sUVuiCCRXqMd72oQuIFAgPpBlEfUdZ2lFX
            BSEbrN5ledMHVIgH4RrVMpcID/dO0umOjWocZ2yK/23E/QN7dUGTUTqMnXoWebo1RYgZJo
            wauoxZ9GM9lrLBjoSTK4OiKlYr+tHa7k4Lmcv6m4xa5HVCVVmQyS8K+lLcQ4r5pXszIjMp
            EAAAdQJp265yaduucAAAAHc3NoLXJzYQAAAgEAwbGwUEvVbv8jdDjLeBU9O3imM9qjcIUr
            43Xr/bNfailOvdXNYmPJSuYoeFGrAR7jkMbbZW4XSd8o2w5Cgiv9bs/OCvgjk9M0Xj8534
            KVlKGAWJw5XN4ZKCVOGSdO9/bFv63A7PW597Q3KBXXIGnwkmV5y8k9vRHfO7lje+v0Nyje
            8D9p6O4wTSRQx+xpw2IiaUnIJbo3+HTKZTrlJLDWK89Z8B2KVraM6edWZe6VfLEkv8+hqb
            gi5x+Fg4WeO9c54mAY6sY4fCLBXTL9DQ9EarY48kTLl5Z3ntw7yGXs+CtGglnt3l+3DSL9
            djCz5puk9XybydzGCgla5FXxN5QI2WeljD22lB8YjgFiU+Cyt/g/EyaUm6rK0HVzPmMjBC
            ivI14m0Q7UEIyonZCAkWQS3KJm9JHjVUkaabZPqCeuZAiQP1S9dGrNFgMYWm3CM0/+d7l7
            vRO8TyAQuF/XmHHnd2TzaKyubwKroiRGcm2Fl0MMpAFFBDxOwC+OeIZ+sUVuiCCRXqMd72
            oQuIFAgPpBlEfUdZ2lFXBSEbrN5ledMHVIgH4RrVMpcID/dO0umOjWocZ2yK/23E/QN7dU
            GTUTqMnXoWebo1RYgZJowauoxZ9GM9lrLBjoSTK4OiKlYr+tHa7k4Lmcv6m4xa5HVCVVmQ
            yS8K+lLcQ4r5pXszIjMpEAAAADAQABAAACAGQk1p/tVWCaEV6ZrrlbYdlJu8S7mh0m/VYR
            Nf5pqz9cNBX6YMIqDXzoGqx6rQtbSRUle3GpxeivtJPtf32F+PY+Aq2xNdPMMxs3XViuT2
            AVUCKAQzg8rI0RHJvssuuJbxx3XXQmaAwl5Q6YnC1qGLPYO2ydk4oZn21loIYFrLKIMxvL
            7Zo87EQ2Ln3vQY9/QYNmXlEDQsT2vV4xYR/jPhhQkJOQ8mF66MhWj1kMTcW2YOW7GD6Dsa
            gFqCYkA3e1A3yDat6XtcSYw5jIMAV8i0cRB8hawViSty4vd8lYyXhWB5KFpHKA0ke8e4eM
            DreAaX1y+6kWuF2gEJpVxO2TYC8AxcMHOczHcc2EVkFze7RSwbDTb+NNmQGG8uliHG30X9
            lbXIGiTrrgNfHCRWTlU0ldXKg8nHmVZQSrKGLIMKxPjlwh+Yf5KTiAzzZvTQwyDlmlZ5Zf
            Y1N0xCulNOEgeAuo1b1wXfp9X2CHOQhh2HLZTo0klbnWa8E2T4NpfgfOixV0PnB8rcUPqd
            KJ/bPGA+Cm5ePIUD0jcGtXqvxT04NzIqwqqdrIeoNxpb79c98fe99bsPBvPyGcY6rZn910
            Sb2tSlfLtT7+EHVOAomlZbC5uOXpT4EnoWxm8lX8BCUG78YgID3pluNzqXbP+hD4OE8ZQJ
            ubiWMEkB9MZ+IzechBAAABAQC/zFCQPl9cgGSIAzTlp4FYjSFbdiJT9e3HlaqzQHQ6Z1w6
            0EmleMfSmZ6HPPfnzlo3gKsxufOqW+KOSoVlpVaItZvPRNwtYhNJnwgsbxdUzs4Zj68Bo+
            FwwrN85r8iTopmCCLhHmJEpfpHj6g0W+OGKyx5o5XbQA5oUxWDWW4GCq+V5Tzd5V9SswOc
            VHIpkp+vugkkrbhy4Y2FHIpKShXGbQYmR4N8bEcg+gzlCuNP7dTc+BeHQw2txAxZqhsB7t
            CkAI/soIuhVUAarQH25/vrD5BzzogkId2tI7pMat+oN78ae1yO0EoL1t3avlCK+UyEorFo
            6mamdiLH9qBR+tv0AAABAQDrYKW8BCzFl/8Op1mPyA3roo7+yF0Ok0GftimUk1Ax1S2b65
            uoqx6z88uun+Nl/ipaNiu0+8+HY3F8gsNxlT+crtuz1QsVXzsYVPACd0vF6PNgwnfp5mnF
            J7vBFfYwaMVIkns/YouAiGj0igLm0CTp4rE6cgAjy+QIagVb5yVD85DWt63fJg273DS4e/
            2/BKnTL08QTfgnyNa2axjdU21DRxXbHA9FGqZK9CopzgBmmqUkuQ2L7rRGrXyN+C+rZIb4
            6FloA8pgymEQuZX9lDDFeuhVBt5KaheXEY+zPoUwoY1tyys0mIjRQ8it/G/zOw9yH593Ua
            qw6vseS17FcpYdAAABAQDSqhx5MteFB+ExYTVqLCdyYTIwMZ1Pkynl34fKA7hPWrew9g5V
            JJV/+NT2ldRC+5fGA7ahVXquiPz/1DjupTYwgbZuTkVZxZqIEIO5oPJdfTyic/nFN8JrUq
            KsOxqGNUIi5U6xDkb4QaQtsxH4on42N9TVnFvLllrp0amGoiy+4dZiFpRs0yZzvIWRlSxw
            hRAW+MgJAOI0RsELpsyj9riok2NX4DXOT/oE5Wut/Viv90YKkx5qHfgjsKdL+LRZIBzWSJ
            sHkEWZpxBZnNwEwi8C4c/thOS8T5AbAsWGgS4LJ99QAve4LJTQFDPmv9ardeZmQu1mWEw9
            f4pDHlJYHBQFAAAAFHdxdWludGFsQGFsYm9yZWEuY29tAQIDBAUG
            -----END OPENSSH PRIVATE KEY-----
        image: ghcr.io/growbe2/growbe-cloud/growbe-cloud:{{ .Values.cloud.version }}
        imagePullPolicy: Always
        name: growbe-cloud
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
          #volumeMounts:
          #- mountPath: /home/node/app/template/releases
          #name: growbe-cloud-releases
        livenessProbe:
          httpGet:
            path: /live
            port: http
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 3
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: ghrc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
status: {}
