apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: nms
  name: nms
spec:
  ports:
  - name: "1935"
    port: 1935
    targetPort: 1935
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: nms
status:
  loadBalancer: {}
