apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pgsql
  name: pgsql
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      io.kompose.service: pgsql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pgsql
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: defaultdb
        - name: POSTGRES_HOST_AUTH_METHOD
          value: md5
        - name: POSTGRES_PASSWORD
          value: test
        - name: POSTGRES_USER
          value: test
        image: postgres
        imagePullPolicy: Always
        name: pgsql
        ports:
        - containerPort: 5432
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pgsql
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pgsql
        persistentVolumeClaim:
          claimName: pgsql
status: {}