
growbe-cloud-chart:
  cloud:
    env: dev
    basePath: dev.growbe.ca
    externalIP: 10.0.4.40
    http:
      certSecret: growbe-ingress-cert
    
    broker:
      port: 1884
      portws: 9002

    confgenerator:
      gh_pat: xxxxxx
      id_rsa: xxxxxx

    nms:
      enabled: true
    auth:
      username: testadmin
      password: "123345678"

    mongo:
      auth:
        username: doadmin
        password: test

    pgsql:
      auth:
        username: test
        password: test

    sso:
      email:
        auth:
          username: apikey
          password: xxxxxx
        from: '"Growbe Cloud" <robot@growbe.ca>'
        redirect: https://cloud.dev.growbe.ca
      settings: '{"publicCreation":true,"multiFactor":false,"accountValidation":true, "defaultRoles": []}'
      secret:
        otp: "123456"
        jwt: 2342tf
