
growbe-cloud-chart:
  deployment:
    affinity: {}
  cloud:
    env: prod
    basePath: growbe.ca
    externalIP: 84.145.234.106
    http:
      certSecret: growbe-ingress-cert
    broker:
      port: 30045

    sshproxy:
      enabled: true
      port: 30050

    prometheus:
      enable: false
    
    backup:
      enabled: true
    
    nms:
      enabled: false
    sso:
      email:
        from: '"Growbe Cloud" <robot@growbe.ca>'
        redirect: https://cloud.growbe.ca
      settings: '{"publicCreation":true,"multiFactor":false,"accountValidation":true, "defaultRoles": []}'
