version: '3'
services:
  pgsql:
    image: postgres 
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=defaultdb
      - POSTGRES_HOST_AUTH_METHOD=md5
    networks:
      - net
    volumes:
      - pgsql:/var/lib/postgresql/data
    ports:
      - '0.0.0.0:5432:5432'
  mongo:
    image: mongo
    restart: always
    networks:
      - net
    ports:
      - '0.0.0.0:27018:27018'
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: "growbe"
      MONGO_INITDB_ROOT_USERNAME: doadmin
      MONGO_INITDB_ROOT_PASSWORD: test
    command: mongod --port 27018
  broker:
    image: eclipse-mosquitto
    networks:
      - net
    ports:
      - '0.0.0.0:1883:1883'
      - '0.0.0.0:9001:9001'
    volumes:
      - type: bind
        source: './mosquito/mosquito.conf'
        target: '/mosquitto/config/mosquitto.conf'
  growbe-cloud:
    image: docker.pkg.github.com/growbe2/growbe-cloud/growbe-cloud:latest
    networks:
      - net
    depends_on:
        - pgsql
        - broker
    ports:
      - '0.0.0.0:3000:3000'
    expose:
      - '3000'
    environment:
      PORT: 3000
      NMS_TOKEN: '12345678'
      NMS_API_USERNAME: 'testadmin'
      NMS_API_PASSWORD: '12345678'
      NMS_API_URL: http://nms:8000
      SSO_URL: 'http://sso:3001'
      DB_URL: 'postgres://test:test@pgsql:5432/defaultdb'
      MONGO_URL: 'mongodb://doadmin:test@mongo:27018/growbe?authSource=admin'
      MQTT_URL: 'mqtt://broker:1883'
    command: node dist/growbe-cloud.js
  growbe-cloud-watcher:
    image: docker.pkg.github.com/growbe2/growbe-cloud/growbe-cloud:latest
    networks:
      - net
    depends_on:
        - pgsql
        - broker
    ports:
      - '0.0.0.0:3005:3005'
    expose:
      - '3005'
    environment:
      PORT: 3005
      SSO_URL: 'http://sso:3001'
      DB_URL: 'postgres://test:test@pgsql:5432/defaultdb'
      MONGO_URL: 'mongodb://doadmin:test@mongo:27018/growbe?authSource=admin'
      MQTT_URL: 'mqtt://broker:1883'
    command: node dist/growbe-watcher.js
  sso:
    image: docker.pkg.github.com/berlingoqc/sso:latest
    networks:
      - net
    depends_on:
        - pgsql
    ports:
      - '0.0.0.0:3001:3001'
    expose:
      - '3001'
    environment:
      PORT: 3001
      DB_URL: 'postgres://test:test@pgsql:5432/defaultdb'
      SSO_SETTINGS: '{}'
      EMAIL_FROM: '"Growbe" <>'
      EMAIL_USER: 'apikey'
      EMAIL_PASSWORD: ''
      SMS_SID: ''
      SMS_TOKEN: ''
      SMS_NUMBER: ''
      OTP_SECRET: '12445431'
      JWT_SECRET: '2342tf'
      JWT_TTL: 9600
    command: npm run start
  frontend_dev:
    image: docker.pkg.github.com/growbe2/growbe-cloud/growbe-portal:latest
    networks:
      - net
    ports:
      - '0.0.0.0:8080:80'
    expose:
      - '80'
  red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Toronto
    ports:
      - "1880:1880"
    networks:
      - net
    volumes:
      - node-red-data:/data
  nms:
    image: docker.pkg.github.com/growbe2/growbe-cloud/nms:latest
    networks:
      - net
    ports:
      - '0.0.0.0:1935:1935'
      - '0.0.0.0:8000:8000'
    volumes:
      - video:/home/node/app/media
    environment:
      - MQTT_URL=mqtt://broker:1883
      - NMS_TOKEN=12345678
      - NMS_API_USERNAME=testadmin
      - NMS_API_PASSWORD=12345678

volumes:
  mongo:
    driver: local
  pgsql:
    driver: local
  node-red-data:
    driver: local
  video:
    driver: local

networks:
  net:
    driver: bridge
