version: '3'
services:
  fluentd:
    build: ./fluentd
    networks:
      - net
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    networks:
      - net
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.10.1
    networks:
      - net
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
  
  oauth2:
    image: quay.io/oauth2-proxy/oauth2-proxy
    networks:
      - net
    volumes:
      - type: bind
        source: './oauth2/config.cfg'
        target: '/config.cfg'
    ports:
      - "4180:4180
    command: --config /config.cfg
  
  growbe-cloud:
    depends_on: 
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  growbe-cloud-watcher:
    depends_on: 
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access