version: '3'
services:
   sso:
     command: bash -c "npm run migrate && npm run start"
   frontend_dev:
      volumes:
      - ${PWD}/docker/config/config.json:/usr/share/nginx/html/growbe-portal/assets/config/config.json