/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModuleDataRequest } from './moduleDataRequest';


export interface DashboardLastValueElement { 
    name?: string;
    type?: DashboardLastValueElement.TypeEnum;
    graphDataConfig?: ModuleDataRequest;
}
export namespace DashboardLastValueElement {
    export type TypeEnum = 'graph' | 'average' | 'lastread' | 'clock';
    export const TypeEnum = {
        Graph: 'graph' as TypeEnum,
        Average: 'average' as TypeEnum,
        Lastread: 'lastread' as TypeEnum,
        Clock: 'clock' as TypeEnum
    };
}


