/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GraphDataConfig } from './graphDataConfig';
import { ModuleDataRequest } from './moduleDataRequest';


export interface DashboardGraphElement { 
    name?: string;
    type?: DashboardGraphElement.TypeEnum;
    graphType?: DashboardGraphElement.GraphTypeEnum;
    graphConfig?: GraphDataConfig;
    graphDataConfig?: ModuleDataRequest;
}
export namespace DashboardGraphElement {
    export type TypeEnum = 'graph' | 'average' | 'clock';
    export const TypeEnum = {
        Graph: 'graph' as TypeEnum,
        Average: 'average' as TypeEnum,
        Clock: 'clock' as TypeEnum
    };
    export type GraphTypeEnum = 'line' | 'bar-vertical';
    export const GraphTypeEnum = {
        Line: 'line' as GraphTypeEnum,
        BarVertical: 'bar-vertical' as GraphTypeEnum
    };
}


