/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GraphDataConfig { 
    legend?: boolean;
    showLabels?: boolean;
    xAxis?: boolean;
    yAxis?: boolean;
    showYAxisLabel?: boolean;
    showXAxisLabel?: boolean;
    yAxisLabel?: string;
    xAxisLabel?: string;
}

