/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrowbeDashboardItemWithRelations } from './growbeDashboardItemWithRelations';


/**
 * (tsType: GrowbeDashboardWithRelations, schemaOptions: { includeRelations: true })
 */
export interface GrowbeDashboardWithRelations { 
  [key: string]: object | any;


    id?: string;
    userId?: string;
    name?: string;
    sidePanel?: object;
    growbeDashboardItems?: Array<GrowbeDashboardItemWithRelations>;
}

