/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Omit<Partial<GrowbeModule>, >, schemaOptions: { title: \'\', partial: true, exclude: [] })
 */
export interface GrowbeModulePartial { 
  [key: string]: object | any;


    id?: string;
    uid?: string;
    connected?: boolean;
    readCount?: number;
    config?: object;
    mainboardId?: string;
    moduleName?: string;
}

