/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export interface DashboardClockStateElement {
    name?: string;
    type?: DashboardClockStateElement.TypeEnum;
    id?: string;
}
export declare namespace DashboardClockStateElement {
    type TypeEnum = 'graph' | 'average' | 'lastread' | 'clock';
    const TypeEnum: {
        Graph: TypeEnum;
        Average: TypeEnum;
        Lastread: TypeEnum;
        Clock: TypeEnum;
    };
}
