/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrowbeWarningKeyWithRelations } from './growbeWarningKeyWithRelations';
/**
 * (tsType: GrowbeWarningWithRelations, schemaOptions: { includeRelations: true })
 */
export interface GrowbeWarningWithRelations {
    id?: number;
    growbeMainboardId?: string;
    warningKeyId?: string;
    text?: string;
    data?: object;
    createdAt?: string;
    warningKey?: GrowbeWarningKeyWithRelations;
}
