/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrowbeMainboardConfigWithRelations } from './growbeMainboardConfigWithRelations';
import { GrowbeModuleWithRelations } from './growbeModuleWithRelations';
import { GrowbeModuleDefWithRelations } from './growbeModuleDefWithRelations';
import { GrowbeWarningWithRelations } from './growbeWarningWithRelations';
import { VirtualRelayWithRelations } from './virtualRelayWithRelations';
import { GrowbeSensorValueWithRelations } from './growbeSensorValueWithRelations';
import { UserWithRelations } from './userWithRelations';
import { GrowbeLogsWithRelations } from './growbeLogsWithRelations';
/**
 * (tsType: GrowbeMainboardWithRelations, schemaOptions: { includeRelations: true })
 */
export interface GrowbeMainboardWithRelations {
    id?: string;
    name?: string;
    state?: string;
    userId?: string;
    organisationId?: string;
    lastUpdateAt?: string;
    version?: string;
    cloudVersion?: string;
    user?: UserWithRelations;
    organisation?: UserWithRelations;
    growbeMainboardConfig?: GrowbeMainboardConfigWithRelations;
    growbeWarnings?: Array<GrowbeWarningWithRelations>;
    growbeSensorValues?: Array<GrowbeSensorValueWithRelations>;
    growbeModules?: Array<GrowbeModuleWithRelations>;
    growbeLogs?: Array<GrowbeLogsWithRelations>;
    growbeModuleDefs?: Array<GrowbeModuleDefWithRelations>;
    virtualRelays?: Array<VirtualRelayWithRelations>;
}
