/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserWithRelations } from './userWithRelations';
import { OrganisationWithRelations } from './organisationWithRelations';
/**
 * (tsType: OrganisationInvitationWithRelations, schemaOptions: { includeRelations: true })
 */
export interface OrganisationInvitationWithRelations {
    id?: number;
    organisationId?: string;
    userId?: string;
    response?: string;
    organisation?: OrganisationWithRelations;
    user?: UserWithRelations;
}
