/**
 * growbe-cloud
 * Cloud server for Growbe
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: wquintal@berlingoqc.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtraFieldWithRelations } from './extraFieldWithRelations';
import { OrgUserLinkWithRelations } from './orgUserLinkWithRelations';
import { UserWithRelations } from './userWithRelations';
/**
 * (tsType: OrganisationWithRelations, schemaOptions: { includeRelations: true })
 */
export interface OrganisationWithRelations {
    name?: string;
    thumbnailURL?: string;
    bannerURL?: string;
    id?: string;
    type?: string;
    extraFields?: ExtraFieldWithRelations;
    managerId?: string;
    manager?: UserWithRelations;
    users?: Array<OrgUserLinkWithRelations>;
}
