name: growbe cloud pipeline

on:
  push:
    tags:
      - 'cloud*'

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Docker build
        run: cd growbe-cloud && npm install && npm run docker:build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Publish
        run: cd growbe-cloud && npm run docker:push
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
 
 