name: growbe cloud pipeline

on:
  push:
    branches:
      - master

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Login docker
        run: docker login https://ghcr.io -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
        with:
            node-version: '10.x'
            registry-url: 'https://npm.pkg.github.com'
            scope: '@growbe2'
      - name: Installing helm3
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
      - name: Setting kubeconfig
        run: mkdir -p $HOME/.kube && echo "${{ secrets.KUBECONF }}" > $HOME/.kube/config
      - name: Updating version
        run: echo "VERSION=$(npm run getversion --silent)" >> $GITHUB_ENV
      - name: Portal docker-build
        run: cd growbe-portal && npm --no-git-tag-version version ${VERSION} && npm run docker:build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Cloud docker-build
        run: cd growbe-cloud && npm --no-git-tag-version version ${VERSION} && npm run docker:build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Publish Cloud
        run: cd growbe-cloud && npm run docker:push
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Publish Portal
        run: cd growbe-portal && npm run docker:push
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Build and release migration image
        run: cd transactional/ && ./docker/migration_docker_release.sh
      - name: Deploy migration job to k8s
        run: cd transactional/ && ./docker/migration_k8s.sh
        env:
          DB_URL: ${{ secrets.DB_PROD }}
          MONGO_URL: ${{ secrets.MONGO_PROD }}
          NAMESPACE: growbe-prod
      - name: Deploy
        run: KUBECONFIG=$HOME/.kube/config ./helm/deploy.sh --namespace=growbe-prod --set=growbe-cloud-chart.cloud.version=${VERSION} --values=./helm/values/prod.yaml
      - name: Notify
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to dev. ${{ github.event.head_commit.message }}'