name: growbe cloud pipeline

on:
  push:
    branches:
      - develop

jobs:
  proxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
        with:
            node-version: '10.x'
            registry-url: 'https://npm.pkg.github.com'
            scope: '@growbe2'
      - name: Updating version
        run: npm run setversion:develop
      - name: Portal docker-build
        run: cd growbe-portal && npm run docker:build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Cloud docker-build
        run: cd growbe-cloud && npm run docker:build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Publish Cloud
        run: cd growbe-cloud && npm run docker:push
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Publish Portal
        run: cd growbe-portal && npm run docker:push
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Deploy to dev
        run: 'mkdir $HOME/.ssh && echo "${{secrets.SSH2}}" > $HOME/.ssh/id_rsa && chmod 700 $HOME/.ssh/id_rsa && ssh -oStrictHostKeyChecking=accept-new root@api.growbe.wquintal.ca "cd growbe-cloud && git pull origin master && ./docker/deploy.sh"'
