name: growbe cloud PR approuval

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  growbe-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Updating version
        run: echo "VERSION=$(npm run getversion:develop --silent)" >> $GITHUB_ENV
      - name: Setting npmrc
        run: echo "${{ secrets.NPMRC }}" > $HOME/.npmrc
      - name: Install pgsql client
        run: sudo apt-get install postgresql
      - name: Running test 
        run: ./scripts/integration.sh test
  growbe-portal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login docker
        run: docker login https://docker.pkg.github.com -u berlingoqc -p $GITHUB_ACCESS_TOKEN
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Running build
        run: cd growbe-portal && VERSION=test npm run docker:build
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PAT }}
